### ISSUE TITLE
Possibly do 2E transfer instead of 3E

### ISSUE THREAD

**Issue by niklasekstrom** [cnvogelg/plipbox#11]
Hi Christian,

I was looking at your parallel port communication code, and at your blog https://lallafa.de/blog/2015/09/amiga-parallel-port-how-fast-can-you-go/, and I was thinking that by doing a small optimization it might be possible to do 2E reads and writes instead of 3E.

I did the change as a commit here: https://github.com/niklasekstrom/plipbox/commit/4e5b1ecefaef79bef1dbcd67cdff6ebc5c1d99e0

My thinking is that the bset/bclr instructions are read-modify-write instructions, so an instruction is first doing a read from the CIA register of the old value and then a write to the CIA register of the updated value. By instead doing a single write it should be possible to remove an access to a CIA register, which saves one E-cycle.

Here I'm assuming that you have an accelerator which is sufficiently much faster so that the instruction fetch time is hidden.

Note that I don't own a plipbox myself so I haven't had a chance to test this. I'm not sure if the AVR-side will be able to keep up at the higher pace.

Feel free to close this issue if this suggestion wouldn't be useful.

**Comment by niklasekstrom** [comment]
I have now verified that this method works, with this parallel port to SPI adapter: https://github.com/niklasekstrom/amiga-par-to-spi-adapter.

**Comment by cnvogelg** [comment]
2E is the way to go. I already use it in my follow up project [amiparbox](https://github.com/cnvogelg/amiparbox). The avr part is written in assembler now to have robust transfers. For the new teensy 3.2 arm support C is fast enough.

**Comment by niklasekstrom** [comment]
I see, cool. From a very quick glance at your amiparbox repo, I guess the solution I came up with is a bit simpler, as the AVR is acting as a "glorified shift register" that shifts out SPI bits at >8x the rate that it receives bytes from the Amiga. Any processing needs to be done by the Amiga. One benefit is that there is no buffering in the AVR, so the time until the Amiga receives the transferred data is minimal.

Do you have any plans to update plipbox to do 2E? Otherwise I guess this issue could be closed.

Once I receive a ENC28J60 module and can test that it works with my adapter and Mike Sterling's [driver](https://github.com/mikestir/k1208-drivers/tree/master/net) I think it should be possible to do a firmware upgrade of an existing plipbox device and run my firmware and software instead to do 2E transfers (assuming that ends up giving better performance).

**Comment by cnvogelg** [comment]
I really like your project, too. Its simple but very effective :)

The goals with the amiparpbox project are a bit different: I want to provide access to all of the mcu's interfaces including SPI, I2C, and even serial or GPIO and therefore I am developing a protocol on the parallel port that allows to multiplex those data channels. Second I want to offload the Amiga as much as possible and implement drivers (SD Card, Network, Display I/O, ...) on the MCU so that the channels only transport "high-level" data like network packets or data blocks of an sd card. On the Amiga side you have a single device that allows to access the multiplexer (called pamela.device) and standard devices like block devices or sana2 devices use the pamela.device to access their data channels on the amiparbox.

Next to the new teensy 2.0 and teensy 3.2 boards developed for amiparbox I still support the classic plipbox HW and even support an sd card add on there. So with amiparbox SW ready (hopefully some time in the not so distant future :)) it will completely replace the plipbox SW. Therefore develop on plipbox is stopped for now and I focus on amiparbox only.

If the amiparbox projects sparks your interest then I'd be more than happy if you give it a try... Unfortunately, currently the full SW stack is not finished yet and user docs are missing completely :( Feel free to ask if you need support...

**Comment by drummerjoe** [comment]
Excited to see where this goes.  I love my Plipbox.
